dist: bionic

language: python

arch:
    - amd64
    - arm64-graviton2

virt: lxd

group: edge

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip3 install -r requirements-dev.txt

before_script:
    - printenv | sort

script:
    - ./run_tests -v
